"""
Gemini PR Code Reviewer

Reviews a GitHub Pull Request diff using Vertex AI Gemini API and posts
structured findings as PR comments.

Authentication: Uses Application Default Credentials (ADC) set by
google-github-actions/auth in the calling workflow. No explicit key needed.

Environment variables expected:
  GCP_PROJECT_ID        - GCP project ID
  GCP_REGION            - Vertex AI region (default: us-central1)
  GEMINI_MODEL          - Model ID (default: gemini-2.5-pro)
  GITHUB_TOKEN          - GitHub PAT for posting comments
  GITHUB_REPOSITORY     - owner/repo (set by GitHub Actions)
  GITHUB_PULL_REQUEST_NUMBER - PR number (set by GitHub Actions)
  REVIEW_MAX_TOKENS     - Max output tokens (default: 8192)
  REVIEW_TEMPERATURE    - Model temperature (default: 0.3)
"""

import json
import os
import subprocess
import sys
from urllib import error, request

from review_prompt import (
    build_review_prompt,
    extract_json,
    get_pr_changed_files,
    get_pr_diff,
    post_comment,
    post_inline_comments,
)


def call_gemini(prompt):
    """Call Vertex AI Gemini API using ADC auth token."""
    project_id = os.environ["GCP_PROJECT_ID"]
    region = os.environ.get("GCP_REGION", "us-central1")
    model = os.environ.get("GEMINI_MODEL", "gemini-2.5-pro")
    max_tokens = int(os.environ.get("REVIEW_MAX_TOKENS", "8192"))
    temperature = float(os.environ.get("REVIEW_TEMPERATURE", "0.3"))

    url = (
        f"https://{region}-aiplatform.googleapis.com/v1/"
        f"projects/{project_id}/locations/{region}/"
        f"publishers/google/models/{model}:generateContent"
    )

    token_result = subprocess.run(
        ["gcloud", "auth", "print-access-token"],
        capture_output=True,
        text=True,
    )
    if token_result.returncode != 0:
        raise RuntimeError(f"Failed to get auth token: {token_result.stderr}")
    access_token = token_result.stdout.strip()

    payload = json.dumps(
        {
            "contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens,
                "topP": 0.95,
            },
        }
    ).encode("utf-8")

    req = request.Request(url, data=payload, method="POST")
    req.add_header("Authorization", f"Bearer {access_token}")
    req.add_header("Content-Type", "application/json")

    try:
        with request.urlopen(req, timeout=120) as resp:
            response_body = json.loads(resp.read().decode("utf-8"))
    except error.HTTPError as e:
        raise RuntimeError(f"Gemini API error {e.code}: {e.read().decode()}")

    try:
        text = response_body["candidates"][0]["content"]["parts"][0]["text"]
    except (KeyError, IndexError):
        raise RuntimeError(
            f"Unexpected response format: {json.dumps(response_body, indent=2)}"
        )

    return text


def format_comment(review_data):
    """Format review findings into a GitHub comment body."""
    findings = review_data.get("findings", [])
    summary = review_data.get("summary", "No summary provided.")
    verdict = review_data.get("verdict", "comment")
    suggestions = review_data.get("suggestions", [])

    severity_icons = {
        "critical": "\U0001f534",
        "high": "\U0001f7e0",
        "medium": "\U0001f7e1",
        "low": "\U0001f535",
        "info": "\u26aa",
    }
    verdict_labels = {
        "approve": "\u2705 Approve",
        "request_changes": "\u274c Request Changes",
        "comment": "\U0001f4ac Comment",
    }

    lines = [
        "## \U0001f916 Gemini Code Review",
        "",
        f"**Verdict:** {verdict_labels.get(verdict, verdict)}",
        "",
        f"> {summary}",
        "",
    ]

    if not findings:
        lines.append("No issues found. Great work! \U0001f389")
        return "\n".join(lines)

    lines.append("### Findings")
    lines.append("")

    for i, finding in enumerate(findings, 1):
        icon = severity_icons.get(finding.get("severity", "info"), "\u26aa")
        category = finding.get("category", "general")
        title = finding.get("title", "Issue")
        description = finding.get("description", "")
        file_path = finding.get("file", "")
        line_info = finding.get("line", "")

        location = f"`{file_path}`"
        if line_info:
            location += f" (near {line_info})"

        lines.append(
            f"#### {i}. {icon} [{finding.get('severity', 'info').upper()}] {title}"
        )
        lines.append(f"**Category:** {category} | **File:** {location}")
        lines.append("")
        lines.append(description)
        lines.append("")

    if suggestions:
        lines.append("### Suggestions")
        for s in suggestions:
            lines.append(f"- {s}")

    lines.append("")
    lines.append("---")
    lines.append("*Review generated by Gemini (Vertex AI) in CI/CD pipeline*")

    return "\n".join(lines)


def main():
    print("=== Gemini PR Code Reviewer ===")

    required = [
        "GCP_PROJECT_ID",
        "GITHUB_TOKEN",
        "GITHUB_REPOSITORY",
        "GITHUB_PULL_REQUEST_NUMBER",
    ]
    missing = [v for v in required if v not in os.environ]
    if missing:
        print(f"ERROR: Missing environment variables: {', '.join(missing)}")
        sys.exit(1)

    model = os.environ.get("GEMINI_MODEL", "gemini-2.5-pro")
    print(f"Model: {model}")
    print(f"Project: {os.environ['GCP_PROJECT_ID']}")
    print(f"Region: {os.environ.get('GCP_REGION', 'us-central1')}")

    print("Fetching PR diff...")
    try:
        diff = get_pr_diff()
    except RuntimeError as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    if not diff.strip():
        print("No diff found. Skipping review.")
        return

    print(f"Diff size: {len(diff)} chars across {diff.count('diff --git')} files")
    changed_files = get_pr_changed_files()
    print(f"Changed files: {len(changed_files)}")

    print("Building review prompt...")
    prompt = build_review_prompt(diff, changed_files)

    print(f"Calling Gemini ({model})...")
    try:
        response_text = call_gemini(prompt)
    except RuntimeError as e:
        print(f"ERROR calling Gemini: {e}")
        post_comment(
            "## Gemini Code Review\n\n"
            "\u274c **Review failed.** The AI model could not complete the "
            f"review.\n\nError: {e}",
            tmpfile_prefix="gemini-review",
        )
        sys.exit(1)

    print("Parsing Gemini response...")
    try:
        review_data = extract_json(response_text)
    except (json.JSONDecodeError, ValueError) as e:
        print(f"ERROR parsing JSON from model response: {e}")
        print(f"Raw response (first 1000 chars): {response_text[:1000]}")
        print(f"Raw response (last 500 chars): {response_text[-500:]}")
        post_comment(
            "## Gemini Code Review\n\n"
            "\u274c **Review failed.** The AI model returned an unexpected "
            "format.\n\nRaw response was logged but could not be parsed as JSON.",
            tmpfile_prefix="gemini-review",
        )
        sys.exit(1)

    findings = review_data.get("findings", [])
    verdict = review_data.get("verdict", "comment")
    print(f"Findings: {len(findings)}, Verdict: {verdict}")

    comment = format_comment(review_data)
    print("Posting review comment...")
    post_comment(comment, tmpfile_prefix="gemini-review")

    if findings:
        post_inline_comments(findings)

    if verdict == "request_changes":
        print("Verdict: REQUEST CHANGES (critical issues found)")

    print("Review complete.")


if __name__ == "__main__":
    main()
